steps:
- bash: |
    go version
    export GOPATH=$(pwd)
    echo "GOPATH: $GOPATH"
    echo "current location: $(pwd)"
    go get -u github.com/kardianos/govendor

    echo "govendor location:"
    find . -iname kardianos
  displayName: check go version

- bash: |
    ./run-checks --static
  displayName: static code checks

- bash: |
    ./run-checks --unit
  displayName: run unit tests  