steps:
- bash: |
    go version
    echo $GOPATH
    go get -u github.com/kardianos/govendor
  displayName: check go version

- bash: |
    ./run-checks --static
  displayName: static code checks

- bash: |
    ./run-checks --unit
  displayName: run unit tests  