steps:
- task: GoTool@0
  inputs:
    # version: '1.13.5'
    version: '1.12.1'

- bash: |
    apt update && apt install tree
  displayName: install 'tree' for diagnostics

- bash: |
    go version
    # export GOPATH=$(pwd)
    echo "GOPATH: $GOPATH"

    tree -d

    # echo "current location: $(pwd)"
    # # go get -u github.com/kardianos/govendor

    # # echo "govendor location:"
    # # find . -iname kardianos
    # ./get-deps.sh
  displayName: check go version

- task: Go@0
  inputs:
    command: get
    arguments: '-d -v'
    workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: get sources for project and dependencies

- bash: |
    tree -d
  displayName: see what we've ended up with

# - bash: |
#     echo "GOPATH: $GOPATH"
#     go get github.com/rjsmith1972/iot-identity
#     ls -l
#   displayName: go get package

# - bash: |
#     ./get-deps.sh
#   displayName: get dependencies
#   workingDirectory: github.com/rjsmith1972/iot-identity

# - bash: |
#     ./run-checks --static
#   displayName: static code checks

# - bash: |
#     ./run-checks --unit
#   displayName: run unit tests  