steps:
- bash: |
    go version
    export GOPATH=$(pwd)
    echo "GOPATH: $GOPATH"

    # echo "current location: $(pwd)"
    # # go get -u github.com/kardianos/govendor

    # # echo "govendor location:"
    # # find . -iname kardianos
    # ./get-deps.sh
  displayName: check go version

- bash: |
    echo "GOPATH: $GOPATH"
    go get github.com/rjsmith1972/iot-identity
    ls -l
  displayName: go get package

- bash: |
    ./get-deps.sh
  displayName: get dependencies
  workingDirectory: github.com/rjsmith1972/iot-identity

# - bash: |
#     ./run-checks --static
#   displayName: static code checks

# - bash: |
#     ./run-checks --unit
#   displayName: run unit tests  